[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Dquarkus.http.host=0.0.0.0 -jar /app/quarkus-app/quarkus-run.jar"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
