
# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${PGUSER:postgres}
quarkus.datasource.password=${PGPASSWORD:Makeover3}
quarkus.datasource.jdbc.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:pa2_db}?sslmode=${PGSSLMODE:disable}

# Puerto y host para Railway
quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0

# Esquema / logs
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true




